version: '3.8'

services:
  # 1. LA BASE DE DATOS (PostgreSQL)
  db:
    image: postgres:15-alpine
    container_name: arbimerge-db
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: rootpassword
      POSTGRES_DB: arbimerge_db
    ports:
      - "5432:5432" # Expone el puerto para que Prisma Studio o pgAdmin puedan conectarse desde tu PC
    volumes:
      - pgdata:/var/lib/postgresql/data # Persistencia: si el contenedor se cae, no pierdes los datos

  # 2. EL BACKEND (Node.js + WebSockets)
  backend:
    build:
      context: ./packages/backend
      dockerfile: Dockerfile
    container_name: arbimerge-backend
    restart: unless-stopped
    depends_on:
      - db
    environment:
      # ¡IMPORTANTE! Nota que usa "db" (el nombre del servicio de arriba) en lugar de "localhost"
      DATABASE_URL: "postgresql://root:rootpassword@db:5432/arbimerge_db?schema=public"
      PORT: 3000
      # POLYGON_API_KEY: tu_api_key_aqui
    ports:
      - "3000:3000"

  # 3. EL FRONTEND (React + Nginx)
  frontend:
    build:
      context: ./packages/frontend
      dockerfile: Dockerfile
    container_name: arbimerge-frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "80:80" # El puerto web por defecto. Accederás a la app en http://localhost

volumes:
  pgdata: